### ISSUE TITLE
Add the Project Creation automation for GitLab

### ISSUE THREAD

**Issue by gmr** [AWeber-Imbi/imbi#11]
Once #10 is complete, create an automation around Project Creation in GitLab when creating the project in Imbi. Leverage the slugs for Namespace and Project Type.

**Comment by dave-shawley** [comment]
@gmr I can't link PRs to this issue but https://github.com/AWeber-Imbi/imbi/pull/56 closed it.

**Comment by dave-shawley** [comment]
Closed by https://github.com/AWeber-Imbi/imbi-api/pull/73
