### ISSUE TITLE
Add SonarQube Project Creation Automation

### ISSUE THREAD

**Issue by gmr** [AWeber-Imbi/imbi#22]
Create an automation in Project Creation for setting up  a project in SonarQube.

**Comment by dave-shawley** [comment]
@gmr closed by https://github.com/AWeber-Imbi/imbi/pull/59 ?

**Comment by dave-shawley** [comment]
CLosed by https://github.com/AWeber-Imbi/imbi-api/pull/77

**Comment by dave-shawley** [comment]
Closed by https://github.com/AWeber-Imbi/imbi-api/pull/77
