### ISSUE TITLE
Add additional optional integration attributes to projects

### ISSUE THREAD

**Issue by gmr** [AWeber-Imbi/imbi#24]
- GitLab Project ID
- SonarQube Project Key
- PagerDuty Service ID

**Comment by dave-shawley** [comment]
@gmr closed by https://github.com/AWeber-Imbi/imbi/pull/52 ?

**Comment by dave-shawley** [comment]
Project IDs in external systems was addressed by https://github.com/AWeber-Imbi/imbi-api/pull/61 and https://github.com/AWeber-Imbi/imbi-ui/pull/70
