### ISSUE TITLE
Hover/tooltip to show desired state

### ISSUE THREAD

**Issue by ryangsteele** [AWeber-Imbi/imbi#5]
IMO, it would be useful to be able to hover over individual items that comprise a project's health score to identify what the desired state should be. For example, if the Programming Language is Python 3.7 and that's flagged with an orange color (because Python 3.9 is desired), having a hover tooltip to show that Python 3.9 is the goal would be good feedback for project maintainers. Since the tooltip already shows the current score, perhaps we could give a hint about the max score, e.g.:

```
Current score: 75
    Max score: 100 (Python 3.9)
```

![Screen Shot 2021-03-22 at 10 21 12 AM](https://user-images.githubusercontent.com/5678706/112005231-f319aa00-8af8-11eb-86c9-c3e2a2eda5a6.png)

**Comment by gmr** [comment]
The only issue with the suggestion here is there are some fact types that have multiple options for max score.

We should play with a comma delimited list of those items or perhaps have a different popup behavior that perhaps is a card or panel with the table of possible values.

**Comment by tomkulzer** [comment]
thread talking about similar theme https://aweber.slack.com/archives/C01SFQYH3A5/p1621354930001300

**Comment by dave-shawley** [comment]
Decided to go a different direction with this one. I added a slide over panel that is displayed when you click on the project score. It could use some UI prettying but it is considerably better than nothing.
![image](https://github.com/user-attachments/assets/15bc97ca-ecca-4e4a-b9ab-10ae04dbd8e4)
