### ISSUE TITLE
Changing the filter in the project view does not reset the paging parameters

### ISSUE THREAD

**Issue by dave-shawley** [AWeber-Imbi/imbi#54]
Say I am on the third page of the unfiltered project view (something like `.../ui/projects?sort=name+asc&limit=100&offset=200`) and I select a namespace to filter by.  The resulting url is `.../ui/projects?namespace_id=5&sort=name+asc&limit=100&offset=200`.  If there is no third page then the result is:

![screen-b40rp image](https://user-images.githubusercontent.com/350812/122929805-5a820880-d339-11eb-8007-3d3808464ae5.png)

Note the `Showing 201 to 53 of 53 records`.  Also clicking on the page number in the lower right does take you to the first page.

**Comment by gmr** [comment]
This is resolved with the change in 0.15 to move to OpenSearch and remove paging.
