### ISSUE TITLE
Searching does not reset page number

### ISSUE THREAD

**Issue by dave-shawley** [AWeber-Imbi/imbi#63]
If you browse to anything but the first page in projects and then search on project name, the result is an empty list with a previous page button as shown below.  You can click the previous page button to see the single page search result.

![screen-e9lws image](https://user-images.githubusercontent.com/350812/135623263-bd09e914-ee4a-4b54-a664-7113f3d2c378.png)

**Comment by gmr** [comment]
This will no longer be an issue due to the refactor of this page in 0.15
