### ISSUE TITLE
Add column sort to Reports

### ISSUE THREAD

**Issue by tomkulzer** [AWeber-Imbi/imbi#7]
Add support for column sorting to Reports.

/ui/reports/namespace-kpis

<img width="1030" alt="2021-03-19_15-31-15" src="https://user-images.githubusercontent.com/6731107/111833173-32ad7f80-88c8-11eb-9e36-da05f8fbca16.png">

**Comment by gmr** [comment]
Given the scope of data for this report, this sorting should be client side only.
