### ISSUE TITLE
User not redirected after deleting a project 

### ISSUE THREAD

**Issue by ryangsteele** [AWeber-Imbi/imbi#74]
When a project is deleted from Imbi, the user should be redirected somewhere (e.g., the projects page). Instead, the user remains on `/ui/projects/{project_id}/settings` with the entire page grayed out:

![Screen Shot 2022-09-23 at 2 48 28 PM](https://user-images.githubusercontent.com/5678706/192038150-fe8daf45-b868-47fe-b0de-114f897a98a0.png)

**Comment by dave-shawley** [comment]
This was addressed somewhere along the way. I verified that deleting a project redirects to either the previous page or the project search page.
