### ISSUE TITLE
Allow selecting of Project in ops-log to fill in earlier qualifiers

### ISSUE THREAD

**Issue by joshehlinger** [AWeber-Imbi/imbi#88]
This is for the operations log:

When selecting a project, I'd like to type in the first couple of letters of it under the "Project" dropdown column and have that fill back in the Namespace and Project Type. This would be a nice QoL thing as then I don't have to remember which of the two dozen different project types my project is in necessarily - maybe filter the options provided in the dropdown of Projects by any qualifier provided. e.g. If a Namespace is selected, the project is selectable but filtered to _every_ project in that namespace (instead of forcing the user to figure out which project type their project is)

**Comment by dave-shawley** [comment]
We can leverage the OpenSearch index for this since we index all of the necessary parts.

**Comment by dave-shawley** [comment]
Decided that the effort to implement this feature was larger than the value provided. We are going to add a project-specific create operations log option instead.
