### ISSUE TITLE
Create customizable content areas: Welcome in dashboard, center of footer

### ISSUE THREAD

**Issue by gmr** [AWeber-Imbi/imbi#9]
Create a database driven "Welcome" section that will display on the dashboard, which allows customization via the admin and renders via markdown.

Similarly, a section in the footer should exist that allows for custom content and links.

Related to internal ticket PSE-6764

**Comment by gmr** [comment]
Footer added, configurable by Imbi's configuration file as a first step.

**Comment by tomkulzer** [comment]
seems like this can close as it's in prod.
